[package]
name = "advent2021-bin"
version = "0.1.0"
edition = "2021"

[dependencies]
advent2021-lib = { path = "../advent2021-lib" }
color-eyre = "0.5"
colored = "2"
indicatif = "0.15"
structopt = "0.3.5"
